/* Pokémon Void — Walkthrough / Guide data.  window.VGUIDE = { CHAPTERS }
   Each chapter layers a concise summary (items / mons / objectives) over the
   full story dialogue. Add new chapters by copying the shape below. Screenshots
   are referenced by repo path under guide-img/ (add the PNGs there to show them);
   a chapter with no images simply omits the `shots` array.

   Dialogue line shape: { who: 'Hickory', text: '...' }
   Use who: '' for narration / action lines (e.g. "Choose your appearance"). */
window.VGUIDE = (function () {
  const CHAPTERS = [
    {
      id: 'intro',
      title: 'Introduction',
      area: 'Opening',
      blurb: "Professor Hickory welcomes you to the world of Pokémon and onboards you as a research intern.",
      summary: {
        objectives: [
          'Customise your character appearance',
          'Choose your name',
          'Meet Professor Hickory and his daughter Pecan',
        ],
        items: [],
        mons: [],
        tip: 'This is a story-only segment — no battles yet. Just enjoy the intro and pick a name you like, since it is used throughout.',
      },
      shots: [],
      dialogue: [
        { who: '???', text: 'Hello? Is this thing working?' },
        { who: '???', text: "Wait I think I've got it—" },
        { who: '???', text: 'Aha! There we go!' },
        { who: '???', text: 'Hello there! Welcome to the world of Pokémon!' },
        { who: 'Hickory', text: 'My name is Hickory, but everyone knows me as the Pokémon Professor!' },
        { who: 'Hickory', text: 'As you know, this world is widely inhabited by the mysterious creatures called Pokémon.' },
        { who: 'Hickory', text: 'Pokémon possess incredible powers and come in countless shapes and forms…' },
        { who: 'Hickory', text: '…they live in forests, oceans, mountains — they can be seen in every corner of our world.' },
        { who: 'Hickory', text: 'We humans live and work alongside Pokémon, supporting one another.' },
        { who: 'Hickory', text: 'Together, we overcome challenges that neither could face alone.' },
        { who: 'Hickory', text: 'Pokémon battles are one way people strengthen their bonds with Pokémon, but research, care, and understanding are just as important.' },
        { who: 'Hickory', text: 'I dedicate my life to studying Pokémon that display different forms and regional phenomenon.' },
        { who: 'Hickory', text: "I'm currently accepting new Pokémon research interns to assist me in my work." },
        { who: 'Hickory', text: "But before we begin... I'd like to learn a little more about you…" },
        { who: 'Hickory', text: "Oh dear, it seems like your camera isn't working on my end." },
        { who: 'Hickory', text: 'Could you turn it on and show me what you look like?' },
        { who: '', text: 'Choose what your player looks like.' },
        { who: 'Hickory', text: "Ah, that's right! You are…" },
        { who: 'Hickory', text: "Err… what's your name again?" },
        { who: '', text: "Pick your player's name. In this guide the player is referred to as <Player>." },
        { who: 'Hickory', text: '<Player> — did I get that right? (Yes / No)' },
        { who: 'Hickory', text: "<Player>, yes! That's the name listed in my files!" },
        { who: '???', text: 'Seriously, Dad? I already organized those files for you!' },
        { who: 'Hickory', text: 'Oh, you know your old man. Always forgetting things.' },
        { who: '???', text: "I really don't know how you managed to mess it up though…" },
        { who: 'Hickory', text: "Let's not worry about that right now, honey." },
        { who: 'Hickory', text: 'Hey, this is a good opportunity to meet <Player>! Come over here for a second, will you?' },
        { who: 'Pecan', text: 'Oh, so this is what <Player> looks like? Nice to meet you, <Player>!' },
        { who: 'Hickory', text: "Meet my daughter, Pecan! She's also my assistant and one of the people you'll be working with." },
        { who: 'Pecan', text: "I'm basically running the lab at this point, dad…" },
        { who: 'Pecan', text: 'Sometimes I wonder if your head is even still attached to your body!' },
        { who: 'Hickory', text: 'Ahhh, what a jokester you are, Pecan.' },
        { who: 'Hickory', text: 'Oh no! I completely forgot about the Pokémon samples!' },
        { who: 'Pecan', text: 'What?! Those were supposed to be taken out half an hour ago!' },
        { who: 'Hickory', text: 'I know, I know…' },
        { who: 'Hickory', text: 'Could you please take care of it, Pecan? I need to finish up onboarding <Player> here…' },
        { who: 'Pecan', text: 'Fine, fine…' },
        { who: 'Hickory', text: 'Now, where was I?' },
        { who: 'Hickory', text: 'Oh yes, right!' },
        { who: 'Hickory', text: "You'll encounter many Pokémon with different perspectives, values, and goals." },
        { who: 'Hickory', text: 'I hope that through this experience, you discover what truly excites you!' },
        { who: 'Hickory', text: 'Build connections with Pokémon, support fellow trainers, and grow!' },
        { who: 'Hickory', text: 'Not just as a researcher, but as a person.' },
        { who: 'Hickory', text: "Now then… let's begin with your Pokémon internship and step into the fascinating world of Pokémon!" },
      ],
    },
    {
      id: 'starter',
      title: 'Starter Selection',
      area: 'Saudade Town',
      blurb: 'Pecan gathers you and your two neighbours to choose your first partner Pokémon.',
      summary: {
        objectives: [
          'Gather your rivals Seren and Ronan from their houses',
          'Return to Pecan and the benches',
          'Choose your starter — you pick first',
        ],
        items: [],
        mons: ['Tamatoo (Grass)', 'and the other two starters'],
        tip: "You get first pick. Seren's house has the yellow roof (southwest); Ronan's has the green roof, next to yours.",
      },
      shots: [],
      dialogue: [
        { who: '???', text: 'Heyyyy!' },
        { who: '???', text: "You're <Player>! Right?" },
        { who: '???', text: 'Hi! Remember me? We met briefly just a while ago on call.' },
        { who: '', text: 'If picked correctly:' },
        { who: 'Pecan', text: "That's me! (Good thing you're not like my dad… always forgetting things…)" },
        { who: 'Pecan', text: "Anyway, you're one of our brand new interns!" },
        { who: 'Pecan', text: 'And whaddya know! You all live right next to each other!' },
        { who: 'Pecan', text: "Isn't that weird?" },
        { who: '<Player>', text: 'I… I guess?' },
        { who: 'Pecan', text: 'Right?' },
        { who: 'Pecan', text: "I've also got some exciting news!" },
        { who: '', text: 'If picked "No…":' },
        { who: '<Player>', text: "No… my mom wouldn't let me get one." },
        { who: 'Pecan', text: "Today's your lucky day then!" },
        { who: 'Pecan', text: 'You see, as part of the internship program, interns get one rare species of Pokémon to accompany them as they work!' },
        { who: 'Pecan', text: "Though… ideally I'd need all of you gathered so you can all pick." },
        { who: 'Pecan', text: "Whose house is whose anyway?" },
        { who: '<Player>', text: "Seren's house is the one with the yellow roof southwest from here." },
        { who: '<Player>', text: "And Ronan's house has a green roof right next to mine." },
        { who: 'Pecan', text: "Well, since I'm sure you're more familiar with them than I am, could you go and get them for me?" },
        { who: 'Pecan', text: "I saw a couple of benches a few steps down from here. I'll wait for you with the Pokémon!" },
        { who: '', text: 'After gathering your rivals:' },
        { who: 'Pecan', text: 'Over here <Player>! Thanks for gathering everyone.' },
        { who: 'Pecan', text: 'I need you guys to step back a lil bit more…' },
        { who: 'Pecan', text: 'Err… two more steps back maybe?' },
        { who: 'Pecan', text: 'Alright! Come out, you guys!' },
        { who: 'Rival 2', text: "WOAHHHHH!!! They're so cute!" },
        { who: 'Rival 2', text: 'I want first dibs!' },
        { who: 'Rival 1', text: "You didn't even remember to check your email, and now you want to get the first pick?" },
        { who: 'Pecan', text: 'Woah, hold on now…' },
        { who: 'Pecan', text: 'I was actually going to let <Player> pick first, seeing as I saw <Player> first.' },
        { who: 'Pecan', text: "Now, <Player>, why don't you check out these adorable little Pokémon?" },
        { who: '', text: 'Starter choice — Tamatoo:' },
        { who: 'Pecan', text: "That's Tamatoo, the Mudcake Pokémon! It's a Grass type, and loves to play in the…" },
      ],
    },
  ];
  return { CHAPTERS };
})();
